from debian:buster

RUN apt-get update && apt-get install -y \
    build-essential clang bison flex \
	libreadline-dev gawk tcl-dev libffi-dev git \
	graphviz xdot pkg-config python3 libboost-system-dev \
	libboost-python-dev libboost-filesystem-dev zlib1g-dev \
    python3 python3-pip iverilog

RUN pip3 install cocotb
RUN pip3 install numpy
